kind: IntegrationRuntime
apiVersion: appconnect.ibm.com/v1beta1
metadata:
  name: ir-01-quickstart
  namespace: mq-ns
spec:
  license:
    accept: false
    license: L-LFMR-BTD75V
    use: CloudPakForIntegrationNonProductionFREE
  replicas: 1
  template:
    spec:
      containers:
        - name: runtime
          resources:
            requests:
              cpu: 300m
              memory: 368Mi
          env:
          - name: MQSI_USE_CALL_HOME_TEST_SOURCE
            value: "true"
  version: '12.0'
