apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  name: admin
  namespace: openshift-operators
  labels:
    eventstreams.ibm.com/cluster: <cluster-name>
    backup.eventstreams.ibm.com/component: kafkauser
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: cluster
        operations:
          - Alter
          - DescribeConfigs
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operations:
          - Create
          - Read
          - Write
          - Delete
          - DescribeConfigs
          - Alter
          - AlterConfigs
      - resource:
          type: topic
          name: __schema_
          patternType: prefix
        operations:
          - Alter
          - Read
      - resource:
          type: group
          name: '*'
          patternType: literal
        operations:
          - Read
          - Delete
